services:
  frontend:
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    ports:
      - "5173:5173" # Vite dev server
      - "4173:4173" # Production preview
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    depends_on:
      - backend

  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    ports:
      - "8080:8080"
    environment:
      - SPRING_PROFILES_ACTIVE=${SPRING_PROFILES_ACTIVE:-prod}
    volumes:
      - ./backend:/app
      - /app/target

volumes:
  node_modules:
