services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    ports:
      - "5173:5173" # Vite dev server
      - "4173:4173" # Production preview
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}
    healthcheck:
      test: >
        sh -c '
          if [ "$$TARGET" = "development" ]; then
            wget --spider -q http://localhost:5173 || exit 1;
          else
            wget --spider -q http://localhost:4173 || exit 1;
          fi
        '
      interval: 10s
      timeout: 5s
      retries: 5

volumes:
  node_modules:
