services:
  frontend:
    restart: unless-stopped
    build:
      context: ./frontend
      dockerfile: Dockerfile
      target: ${TARGET:-production}
    ports:
      - "5173:5173" # Vite dev server
      - "4173:4173" # Production preview
    volumes:
      - ./frontend:/app
      - node_modules:/app/node_modules
    environment:
      - NODE_ENV=${NODE_ENV:-production}

volumes:
  node_modules:
