name: Backend Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build JAR
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          cd backend
          docker build -t springboot-app .

      - name: Run Docker container
        run: |
          cd backend
          docker stop springboot-app || true
          docker rm springboot-app || true
          docker run -d --name springboot-app -p 8080:8080 springboot-app
