name: Java Code Style Check

on:
  push:
    paths:
      - 'backend/**'

jobs:
  checkstyle:
    name: Check Java Code Style
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v3

      - name: Set up JDK 21
        uses: actions/setup-java@v4
        with:
          distribution: 'temurin'
          java-version: '21'

      - name: Build with Maven (skip tests)
        run: |
          cd backend
          mvn compile

      - name: Run Checkstyle
        run:  |
          cd backend
          mvn checkstyle:check
