name: Backend Deployment

on:
  push:
    branches: [main]

jobs:
  deploy:
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Generate JWT keystore
        run: |
          cd backend/src/main/resources
          keytool -genkeypair \
            -keyalg RSA \
            -validity 365 \
            -alias inholland \
            -keystore inholland.p12 \
            -storetype PKCS12 \
            -storepass yourpassword \
            -keypass yourpassword \
            -dname "CN=inholland, OU=TechSage, O=Inholland, L=City, S=State, C=NL"

      - name: Build JAR
        run: |
          cd backend
          mvn clean package -DskipTests

      - name: Build Docker image
        run: |
          cd backend
          docker build -t springboot-app .

      - name: Run Docker container
        run: |
          cd backend
          docker stop springboot-app || true
          docker rm springboot-app || true
          docker run -d --name springboot-app -p 8080:8080 springboot-app
