name: Frontend Deployment

on:
  push:
    paths:
      - "frontend/**"
      - ".github/workflows/frontend.yml"

jobs:
  eslint:
    name: Run ESLint
    runs-on: self-hosted

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Setup Node.js
        uses: actions/setup-node@v4
        with:
          node-version: "22"

      - name: Install pnpm
        uses: pnpm/action-setup@v3
        with:
          version: 10

      - name: Install dependencies
        run: |
          cd frontend
          pnpm install --frozen-lockfile

      - name: Run ESLint
        run: |
          cd frontend
          pnpm run lint:check

  deploy:
    name: Deploy
    runs-on: self-hosted
    if: github.ref == 'refs/heads/main'
    needs:
      - eslint

    steps:
      - name: Checkout code
        uses: actions/checkout@v4

      - name: Build Frontend Docker Image (NGINX)
        run: |
          cd frontend
          docker build \
            --build-arg VITE_APP_URL=${{ secrets.VITE_APP_URL }} \
            --build-arg VITE_API_URL=${{ secrets.VITE_API_URL }} \
            --build-arg VITE_TURNSTILE_KEY=${{ secrets.VITE_TURNSTILE_KEY }} \
            -t vue-app .

      - name: Run Frontend Container
        run: |
          docker stop vue-app || true
          docker rm vue-app || true
          docker run -d --name vue-app -p 80:80 vue-app
